apiVersion: v1
kind: Service
metadata:
  name: riskpredictor-endpoint
  namespace: riskpredictor
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: riskpredictor-endpoint
  type: NodePort
